# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UmMvsDIWSP9ef-Xx07oDHZjTSQp_4He4
"""

import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
embed = hub.load("https://tfhub.dev/google/Wiki-words-500-with-normalization/2")

from numpy.linalg import norm

def cosim(a,b):
  global m
  m=0.
  em1 = embed(a)
  em2 = embed(b)

  print("(",a[-1], ",", b[-1],")",np.inner(em1[-1], em2[-1])/(norm(em1[-1])*norm(em2[-1])))
  m=np.inner(em1[-1], em2[-1])/(norm(em1[-1])*norm(em2[-1]))/(len(a)*len(b))


# a = ["coffee cafe football soccer animal"]
# b = ["soccer coffee cafe cat dog horse"]
# cosim(a,b)
# print(m)